tutorials allow external link
digital4better/laplie pull request #49
Opened 2022-10-21 12:19 UTC by kimslimbou

allow external link for tutorials

2022-11-02 09:40 UTC, KuSh requested changes

2022-11-02 09:40 UTC, KuSh commented on src/lib/components/Tutorials.svelte
> +      {#each tutorials as tutorial}
La dénormalisation ne fonctionnait pas ?

```suggestion
      {#each tutorials as { title, slug, icon, service, url }}
      ...
          <a
            href={url ?? `${base}/tutorials/${tutorial.slug}`}
            target={url ? "_blank" : "_self"}
            class="tutorial--link"
          >
```
```

2022-11-02 09:40 UTC, KuSh commented on src/lib/content/tutorials/se-connecter-sur-pole-emploi.md
> +url : https://www.pole-emploi.fr
Il faut également modifier le paramétrage de netlify et vérifier qu'on est capable d'éditer les contenus en conséquences

Attention, en plus cette URL n'est qu'un test et ne redirige pas vers un vrai tutoriel donc à ne pas inclure dans la PR

2022-11-02 09:40 UTC, KuSh commented on src/lib/types.d.ts
> +export type BaseTutorial = {
Pas besoin de l'exporter et privilégier l'usage d'une interface lorsqu'on veut gérer l'extension (c'est plus explicite)

2022-11-02 09:40 UTC, KuSh commented on src/routes/(tutorials)/tutorials/[slug]/+page.svelte
> +  export let data: PageData & { tutorial: InternalTutorial };
PageData devrait avoir le bon type. Il faut modifier le type de retour de src/routes/(tutorials)/tutorials/[slug]/+page.ts si ce n'est pas le cas

2022-11-16 19:42 UTC, LudaD4B commented on src/lib/components/Tutorials.svelte
> +      {#each tutorials as tutorial}
C'est par rapport au type de Tutorial, il peut soit être InternalTutorial ou ExternalTutorial dans l'un url existe mais pas l'autre du coup au lieu de s'embêter à dire le type on fait pas de dénormalisation, c'est pas très coûteux je trouve

2022-11-16 19:52 UTC, LudaD4B commented on src/routes/(tutorials)/tutorials/[slug]/+page.svelte
> +  export let data: PageData & { tutorial: InternalTutorial };
Ah oui, vu que ce sont forcément des tutos internes, je dois retourner InternalTutorial dans le .ts, c'est ça ?

2022-11-16 19:54 UTC, KuSh commented on src/lib/components/Tutorials.svelte
> +      {#each tutorials as tutorial}
Dans un cas l'URL sera undefined et dans l'autre non. Je ne vois le problème. Je vais regarder

2022-11-16 19:55 UTC, KuSh commented on src/routes/(tutorials)/tutorials/[slug]/+page.svelte
> +  export let data: PageData & { tutorial: InternalTutorial };
un truc du genre oui

2022-11-16 20:03 UTC, LudaD4B commented on src/lib/content/tutorials/se-connecter-sur-pole-emploi.md
> +url : https://www.pole-emploi.fr
Le ficher de config ça doit être svelte.config.js 
Par contre je ne sais pas comment trouver l'interface d'édition de contenu ^^'

2022-11-16 20:07 UTC, KuSh commented on src/lib/content/tutorials/se-connecter-sur-pole-emploi.md
> +url : https://www.pole-emploi.fr
/admin/ sur l'instance locale

2022-11-17 23:18 UTC, KuSh approved these changes
Nickel. J'ai juste revert ta modif sur la config netlify il ne me semble pas qu'on en avait discuté

2022-11-17 23:24 UTC, KuSh approved these changes
Nickel. J'ai juste revert la modification sur la configuration netlify qui ne correspondait pas à l'issue

2022-11-17 23:25 UTC, merged